### ISSUE TITLE
How to get the project root directory for use in a script?

### ISSUE THREAD

**Issue by kolewu** [BobBuildTool/bob#176]
Is there any way to get the project root directory to use it in a script? As a hack I have defined a string substitution plugin that returns the current working directory and use this in a class to set the desired variable.

**Comment by jkloetzke** [comment]
If the `cleanEnvironment` policy is enabled you could reference `$PWD` in `default.yaml`, e.g.:

```yaml
environment:
    PROJECT_ROOT: "${PWD}"
```

But this is usually not a good idea because the built artifacts cannot be shared effectively anymore through an artifact cache because the build location is now part of the input. Can you shed some light on the use case? Maybe there is a better way than to pass in the project root directory...

**Comment by kolewu** [comment]
I'm sure, there is a better way. We use it in a rudimentary project generator for an eclipse derived IDE. There we need the project root at various places. The midterm plan is, to use the eclipse generator for this, but we are not there. In the moment the project root is  given as an environment variable defined in the bob start script. Since this is the last change we maintain on bob master, I would like to remove it  and use vanilla bob from then on.

What does the `cleanEnvironment` policy has to do with the variable available or not? I was under the impression that *cleanEnvironment* means: *No variables are automatically whitelisted* and *non cleanEnvironment* means *`TERM`, `SHELL`, `USER` and home `HOME`* are always whitelisted regardless what the user defines. Where does `PWD` come into the play?

**Comment by kolewu** [comment]
Ahh, it is because with *cleanEnvironment* string substitutions are possible in the config files. That would indeed solve #175, too.

**Comment by kolewu** [comment]
But where is the variable `PWD` coming from? It's not possible to use it in a class even when whitelisted.

**Comment by jkloetzke** [comment]
The documentation doesn't particularly highlight this as a new feature.

The `PWD` variable should be set by the shell (see http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_05_03). At least with Bash it is set:

```sh
bash$ env | grep PWD
PWD=/home/jkloetzke
```

**Comment by jkloetzke** [comment]
Is MSYS different in this case? That would be very strange...

**Comment by kolewu** [comment]
No, MSYS bash does set PWD in the same way. And since the environment of a running process is not changed, this variable always contains the starting directory that by definition is the one containing the `recipes` folder. **BUT** the scripts are executed in a shell and this shell changes the variable. So the variable can only be used reliably in the python code!

**Comment by jkloetzke** [comment]
Interesting. You're right that `PWD` is overwritten in each script by its own shell. The idea was to store it in some other global variable e.g. as `PROJECT_ROOT`. By setting

```yaml
environment:
    PROJECT_ROOT: "${PWD}"
```

in `default.yaml` and then adding `PROJECT_ROOT` to `buildVars` in each recipe you would have it available in the build script.

If the above does not work because `$PWD` is not available you could fall back to a string plugin that uses python `os.getcwd()` and put that in the environment. In `default.yaml` you could have:

```yaml
environment:
    PROJECT_ROOT: "$(get-pwd)"
```

and the string plugin would be:

```python
def getCwd(args, **options):
   return os.getcwd()
manifest = {
    'apiVersion' : "0.2",
    'stringFunctions' : {
        "get-cvwd" : getCwd
    }
}
```

Note: completely untested...

**Comment by kolewu** [comment]
I have used this in a similar plugin, cause we have to support the old bob version as long as the parsing speed is unusable low.

```python
import os


def cwd(args, **kwargs):
    """return the current working directory"""
    return os.getcwd()


manifest = {
    'apiVersion': "0.3",
    'stringFunctions': {
        "cwd": cwd
    }
}
```

But I would prefer a dedicated function or API variable to get the project root directory.

**Comment by jkloetzke** [comment]
Do you start Bob through an MSYS shell or differently? I could imaging that `$PWD` is missing if you execute Bob directory from Windows.

That the project root directory is not available as variable was intentional so far. The problem is that it makes the packages dependent on the file system location of the recipes. It breaks binary artifacts (unless you build in the exact same location) and it won't work on a Jenkins because the paths are different on the server anyway. I think the plugin is the best solution in the meantime until you can move to the eclipse project generator.

**Comment by jkloetzke** [comment]
@kolewu Is this issue still relevant?

**Comment by kolewu** [comment]
Yes, it is still relevant, cause there is no clear way of getting the projects root directory -- the use of _pwd_ throughout the bob code and even more so in independent code like plugins is a hack from my point of view. Not to mention the fact, that it's plain wrong in build scripts.

**Comment by jkloetzke** [comment]
My assumption was that this is only needed because #177 was preventing you from migrating to the latest version.

As described previously I think it is a bad idea that the project root directory is known during package builds. I don't want to encourage this pattern by providing an official function/variable for it. It will break binary artifacts and Jenkins builds. Therefore the current design does not expose this information even internally after the recipes were parsed and the packages were calculated.

If I understood correctly the project root is needed for an Eclipse project generator. Also the built-in generator uses `os.getcwd`. As long as Bob does not support out-of-tree builds I'm ok with this approach because we already rely on that. Once out-of-tree builds will be supported we will have to amend the plugin API to pass the project-root- and build-root-directories explicitly. But I would wait with such a change until there is a real need and the implementation can be tested.

**Comment by jkloetzke** [comment]
@kolewu What kind of root directory do you need in particular? On the long term list there is also the idea to support out-of-tree builds. In this case there are actually two project roots: the recipes root directory and the build root directory. Which one do you need?

Providing the build root directory, for example as `BOB_BUILD_ROOT_PATH` during script execution, should be doable...

**Comment by kolewu** [comment]
We no longer use this rudimentary implementation of a project generator, but I think every generator (be it cmake or any other kind) needs both directories to be able to generate a build configuration.
And although I think it's not clean code to use `pwd` when you want to access the root directory, it makes sense to wait with the change until the implementation of out-of-source builds is tackled.
