### ISSUE TITLE
Jenkins copy artifact of wrong build

### ISSUE THREAD

**Issue by kkendzia** [BobBuildTool/bob#182]
I think Jenkins "Copy artifact" should copy artifacts from last build, even if it failed. In our case quality gates leading to "Failed" status in jobs, although they built correct and published a job. A downstream dependency took the wrong artifact and failed. 
So it would be more correct to take "Last completed build (ignore build status)" instead of "Last successful build" IMHO.

**Comment by jkloetzke** [comment]
But how can you copy an artifact from a failed build? I guess you mean the build was "unstable" due to a post build plugin, e.g. JUnit, right?

Then I think the current "Latest successful build" policy and the proposed "Last completed build (ignore build status)" policy make both sense. It really depends on the use case. Technically Bob will only reuse artifacts as long as the involved recipes are not changes. That is as long as the first job was building from a branch and that branch was not changes Bob may assume that the old artifact is still compatible. 

With a strict policy downstream jobs should only take artifacts that have passed the tests. This is the current behavior. But I do see that it may be desired to ignore that some tests have failed and use the artifacts in the downstream builds nonetheless.

Sounds like an extended option. What do you think?

**Comment by kkendzia** [comment]
An extended option would be nice. I'd go for it.

**Comment by jkloetzke** [comment]
I've looked into it a bit more deeply and I'm not sure that the "Last completed build (ignore build status)" is really useful. It will blindly use the last build of the upstream project even if it could not archive *any* artifacts. In this case the downstream project will fail immediately.

The default policy is to take artifacts from "stable" and "unstable" builds. Why would one ever want to build a downstream project if any of it's upstream projects failed?

Additionally the downstream jobs will only be triggered if the upstream project is "stable". This is currently inconsistent to the "copy artifact" settings that take the last stable or unstable build. To make the behavior consistent failed builds would also trigger downstream builds. That will potentially lead to may failed builds.
