### ISSUE TITLE
complete rebuild on scm change with --build-only

### ISSUE THREAD

**Issue by twsch** [BobBuildTool/bob#198]
### Current situation:
- Build your project
- add some scm overrides in your user.yaml
- Try to rebuild with bob dev --build-only
- bob will rebuild every module affected by the change because of a recipe change, even though the change ONLY affects the scm and shouldn't have any effect on the build process
### Expected behaviour:
changes to the scm part of a recipes shouldn't cause a complete rebuild when building with --build-only

**Comment by jkloetzke** [comment]
I'm not sure that this is possible reliably. This somehow collides with the design of Bob. Based on the recipe Bob calculates the so called Variant-Id. If this Id changes Bob will build clean because it is expected that the change cannot be built incrementally in a reliable way.

On the other hand Bob really does not handle this case well because it will make a clean re-build of the same sources which is annoying but not wrong. But if you later build without '--build-only' Bob will check out the new sources and build incrementally. This is a real bug.

This won't be an easy fix. At the moment I have no good idea and it will considerably change the current build logic.
