### ISSUE TITLE
headline output of `bob status` changed

### ISSUE THREAD

**Issue by gruberchr** [BobBuildTool/bob#228]
The behavior regarding print output of `bob status` changed with PR #226.

Calling `bob status -r <package>` before PR #226 at least printed a headline with the package stack for each recursive checkout step, even if the SCM status is clean. Now with PR #226 printing a headline depends on severity of the SCM status and selected verbosity level.

See function `PackagePrinter.show()`:
```
if severity <= self.verbose:
    self.__printHeader()
```
If SCM status is clean, no output is generated. Even when calling `bob status -vr <package>` (verbosity level `INFO`) no output is generated. You need verbosity level `DEBUG` (`-vv`) to get output (headline).

Is this a desired behavior change of `bob status`? I would expect the same behavior as before or at least a headline with verbosity level `INFO`.

The same question is for the new feature, calling `bob status` without any package. In this case never any output is generated, when SCM status is clean, independent of verbosity level.

Is this desired behavior?

I see that here at first the question is, what should be the content of the headline. At the moment no headline is defined for this case. Bob does not have any package information and therefore can not print the package stack for instance. But Bob could e.g. print the workspace path. And the second question is, when should the headline be printed depending on verbosity level. I would expect the same behavior as calling `bob status` with a package.

**Comment by gruberchr** [comment]
After a hint from @kolewu I see, that this is a desired behavior change and is documented in commit f239720.

**Comment by jkloetzke** [comment]
Just to clarify: this is intended behaviour. The deeper reason is that if you have hundreds of packages you easily miss the important output between all the package paths. Therefore a line is only emitted if something is changed/dirty. You can still see all packages by using `--show-clean` for your use case.

> The same question is for the new feature, calling bob status without any package. In this case never any output is generated, when SCM status is clean, independent of verbosity level.

The same verbosity levels apply here too. You can use `--show-clean` to see which workspace paths were checked.

> And the second question is, when should the headline be printed depending on verbosity level. I would expect the same behavior as calling `bob status` with a package.

The headline is printed only if a package is given to the command. If `bob status` is called without package then packages are irrelevant and are not printed. Partly because they would be ambiguous and mainly because the recipes might not even reference a workspace any more. This was the main reason for the "no-package" mode. It should give you a tool to evaluate the project regardless of the recipes.

BTW, the manpage was updated too and got a chapter for the verbosity settings. Feel free to reopen the ticket if the explanations there are not sufficient.
