### ISSUE TITLE
slow bob checkout check under windows

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#262]
A colleague of mine checked out, why the checkout step in bob is such slow, while bob checks, if any action is necessary for checkout.

After a short investigation, it's a known problem of python:
https://github.com/benhoyt/scandir

Everything important is described in "Background" topic.

But one problem left, we can't use the scandir of >=python-3.5 because for msys2 the platform check against "win32" will fail.

May it's possible to integrate this stuff with some changes, that we check against msys instead of win32.

**Comment by jkloetzke** [comment]
I think the real solution will be to run Bob natively on Windows. Then we can naturally benefit from this optimization in the stdlib because Python 3.5 is anyway required.

But let's keep this issue open until the `os.scandir` optimization is actually implemented. I think it should be not too hard...
