### ISSUE TITLE
bob project --download no

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#264]
bob project includes "--download no" implicitly. I doesn't got, where this come from.

IMO this is not, what we want. Especially also the --exclude flat will be ignored, e.g. we exclude boost and qt lib, than I don't want do download and build **the sources**.

**Comment by jkloetzke** [comment]
> bob project includes "--download no" implicitly. I doesn't got, where this come from.

The rationale is that you want to build and debug the application in your IDE. If we would allow downloads by default the sources of these packages may be missing and the debugging would not work because the debug symbols will point to the wrong path. Hence we build everything from source.

> IMO this is not, what we want. Especially also the --exclude flat will be ignored, e.g. we exclude boost and qt lib, than I don't want do download and build **the sources**.

The exclude option is only to relieve the indexer and to let the user configure what he sees in his IDE. It has no influence on what is built or downloaded.

You can still enable downloads for projects. It's just not the default. But there is no fine grained option to control which packages are downloaded...

**Comment by mahaase** [comment]
Okay, currently I have the view of the performance. May I should really try to debug the project, to see, why that is important. But in the end, building qt and boost, just because of debugging, .... is there another good work process to prevent this?

**Comment by jkloetzke** [comment]
I see that this may be a performance problem. At the moment there is no better option than to use `--download=deps` for your projects.

I think we could add an option to specify exactly what should be downloaded with a regex.

**Comment by jkloetzke** [comment]
Thanks to @rhubert you can now specify `--download packages='boost|qt'`. Only the matching packages will be downloaded while the rest is built locally...
