### ISSUE TITLE
BOB_DEP_PATHS is not set while checkoutScript step

### ISSUE THREAD

**Issue by daxcore** [BobBuildTool/bob#265]
Hey, 

BOB_DEP_PATHS is not set while checkoutScript step. I tested this with basement project:

```
>> containers::lighttpd/devel::pkg-config
   CHECKOUT  dev/src/devel/pkg-config/1/workspace 
### START: Wed Jul 31 20:49:21 CEST 2019
+ _BOB_SOURCES=([0]="Bob prolog")
+ declare -A _BOB_SOURCES
+ trap 'bob_handle_error $? >&2 ; exit 99' ERR
+ trap 'for i in "${_BOB_TMP_CLEANUP[@]-}" ; do rm -f "$i" ; done' EXIT
+ set -o errtrace -o nounset -o pipefail
+ BOB_ALL_PATHS=()
+ declare -A BOB_ALL_PATHS
+ BOB_DEP_PATHS=()
+ declare -A BOB_DEP_PATHS
+ BOB_TOOL_PATHS=()
+ declare -A BOB_TOOL_PATHS
```

But pkg-config has a dependency to 
```
depends:
    - libs::glib-dev
```

**Comment by jkloetzke** [comment]
It may not be documented well but the dependencies are only available in the `buildScript`. The rationale is that the checkout step should just fetch the external resources and should be unaffected by the package dependencies. Otherwise the checkout would have to run again if a package dependency was updated.

**Comment by mahaase** [comment]
Okay, thanks, ur right. That was just an idea, how I could handle recursive cmake dependencies.
a normal cmake install(export) does not force find_package e.g. for dependent static libraries.
So I have to check possibilities for build and package step :)
