### ISSUE TITLE
Increase verbosity level of status code "A" in command "bob status"?

### ISSUE THREAD

**Issue by gruberchr** [BobBuildTool/bob#282]
I have the following use case:

Most of the time I build with Bob option `--build-only` to skip checkout step, which speeds up build time. This may lead to inconsistencies between source code and recipes, if I update the recipes from time to time, since the checkout step is skipped. To check, if my recipes and the code are consistent, I'm using `bob status`, which for example tells me, if I checked out another branch or commit, than stated in the recipe.

But in the following situation `bob status` does not inform me obviously, that my code differs from the recipes. If the source code is clean, but the revision stated in the recipe has changed, only status codes `A` and `N` are active. And any information on that status is only shown, if you use at least verbosity level `-vv`. Furthermore this verbosity level also shows status information on all clean checkouts, which distracts from seeing the inconsistencies.

Due to this use case I'm asking, if

* it's correct, that clean checkouts (no status code) and checkouts with status code `A` should have the same verbosity level
* verbosity level of status code `A` should be the same as for status code `S`, since both cases are inconsistencies between recipe and source code

What's your opinion?

**Comment by jkloetzke** [comment]
I think your suggestion is reasonable. I have never thought about the use case but the current behaviour is indeed inconsistent. Right now only the real checkout is checked and inconsistencies with the recipes are treated as minor incidents. While this is ok if you just care about modifications in the sources (the original inception of the command) it is fatal if you care about the status of the project as a whole.

So yes, I think we should raise the verbosity of `A` and `N` so that they are shown if no extra `-v` was given.
