### ISSUE TITLE
bob build under gnome failed

### ISSUE THREAD

**Issue by frajasalo** [BobBuildTool/bob#357]
When running
  `bob build ...`
in a Gnome session (Gnome terminal) the build fails with:
  `src/namespace-sandbox/namespace-sandbox.c:480: cannot create /tmp/tmpsynzzd1s/run/user: Read-only file system`
Maybe this is caused by the gvfs, but it would be fine if bob can handle it.

System is Debian Buster (10) with all current updates installed.

_Many thanks for your work on bob so far !_

**Comment by frajasalo** [comment]
Output with modification to print _cmdArgs_ in _invoker.py_ and appending `-D` to _cmdArgs_:

```
   CHECKOUT  work/image/rootfs/src/1/workspace 
DEBUG cmdArgs: ['/home/frank/Software/bob/bob/bin/bob-namespace-sandbox', '-D', '-S', '/tmp/tmpbv6l5g_z', '-H', 'bob', '-d', '/tmp', '-M', '/home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/sys', '-m', '/sys', '-M', '/home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/sbin', '-m', '/sbin', '-M', '/home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/proc', '-m', '/proc', '-M', '/home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/lib64', '-m', '/lib64', '-M', '/home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/mnt', '-m', '/mnt', '-M', '/home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/bin', '-m', '/bin', '-M', '/home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/usr', '-m', '/usr', '-M', '/home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/lib', '-m', '/lib', '-M', '/home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/etc', '-m', '/etc', '-M', '/home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/lib32', '-m', '/lib32', '-M', '/home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/run', '-m', '/run', '-M', '/home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/libx32', '-m', '/libx32', '-M', '/home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/root', '-m', '/root', '-M', '/etc/resolv.conf', '-M', '/proc', '-M', '/home/frank/.ssh', '-m', '/nonexistent/.ssh', '-M', '/run/user/1000/keyring/ssh', '-M', '/home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/image/rootfs/src/1/script', '-m', '/.script', '-M', '/home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/image/rootfs/src/1/env', '-w', '/bob/env', '-M', '/home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/image/rootfs/src/1/workspace', '-w', '/bob/a44bd040495fe61bfbdbbc1dab7e90ab3185e9f7/workspace', '-W', '/bob/a44bd040495fe61bfbdbbc1dab7e90ab3185e9f7/workspace', '-M', '/home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace', '-m', '/bob/9dc09c7604593705a191650af51c3e30c5f80ca4/workspace', '--', 'bash', '--', '/.script']
src/namespace-sandbox/namespace-sandbox.c:773: sandbox root is /tmp/tmpbv6l5g_z
src/namespace-sandbox/namespace-sandbox.c:775: working dir is /bob/a44bd040495fe61bfbdbbc1dab7e90ab3185e9f7/workspace
src/namespace-sandbox/namespace-sandbox.c:406: unshare succeeded after 1 tries
src/namespace-sandbox/namespace-sandbox.c:537: createdir: /tmp
src/namespace-sandbox/namespace-sandbox.c:561: mount: /home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/sys -> <sandbox>/sys (ro)
src/namespace-sandbox/namespace-sandbox.c:514: inferred mount options for /tmp/tmpbv6l5g_z/sys: 0
src/namespace-sandbox/namespace-sandbox.c:561: mount: /home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/sbin -> <sandbox>/sbin (ro)
src/namespace-sandbox/namespace-sandbox.c:514: inferred mount options for /tmp/tmpbv6l5g_z/sbin: 0
src/namespace-sandbox/namespace-sandbox.c:561: mount: /home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/proc -> <sandbox>/proc (ro)
src/namespace-sandbox/namespace-sandbox.c:514: inferred mount options for /tmp/tmpbv6l5g_z/proc: 14
src/namespace-sandbox/namespace-sandbox.c:561: mount: /home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/lib64 -> <sandbox>/lib64 (ro)
src/namespace-sandbox/namespace-sandbox.c:514: inferred mount options for /tmp/tmpbv6l5g_z/lib64: 0
src/namespace-sandbox/namespace-sandbox.c:561: mount: /home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/mnt -> <sandbox>/mnt (ro)
src/namespace-sandbox/namespace-sandbox.c:514: inferred mount options for /tmp/tmpbv6l5g_z/mnt: 0
src/namespace-sandbox/namespace-sandbox.c:561: mount: /home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/bin -> <sandbox>/bin (ro)
src/namespace-sandbox/namespace-sandbox.c:514: inferred mount options for /tmp/tmpbv6l5g_z/bin: 0
src/namespace-sandbox/namespace-sandbox.c:561: mount: /home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/usr -> <sandbox>/usr (ro)
src/namespace-sandbox/namespace-sandbox.c:514: inferred mount options for /tmp/tmpbv6l5g_z/usr: 0
src/namespace-sandbox/namespace-sandbox.c:561: mount: /home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/lib -> <sandbox>/lib (ro)
src/namespace-sandbox/namespace-sandbox.c:514: inferred mount options for /tmp/tmpbv6l5g_z/lib: 0
src/namespace-sandbox/namespace-sandbox.c:561: mount: /home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/etc -> <sandbox>/etc (ro)
src/namespace-sandbox/namespace-sandbox.c:514: inferred mount options for /tmp/tmpbv6l5g_z/etc: 0
src/namespace-sandbox/namespace-sandbox.c:561: mount: /home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/lib32 -> <sandbox>/lib32 (ro)
src/namespace-sandbox/namespace-sandbox.c:514: inferred mount options for /tmp/tmpbv6l5g_z/lib32: 0
src/namespace-sandbox/namespace-sandbox.c:561: mount: /home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/run -> <sandbox>/run (ro)
src/namespace-sandbox/namespace-sandbox.c:514: inferred mount options for /tmp/tmpbv6l5g_z/run: 0
src/namespace-sandbox/namespace-sandbox.c:561: mount: /home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/libx32 -> <sandbox>/libx32 (ro)
src/namespace-sandbox/namespace-sandbox.c:514: inferred mount options for /tmp/tmpbv6l5g_z/libx32: 0
src/namespace-sandbox/namespace-sandbox.c:561: mount: /home/frank/Projekte/Bob/Rosho/drx/drx4/build/work/sandbox/debian-stretch-x86_64/dist/1/workspace/root -> <sandbox>/root (ro)
src/namespace-sandbox/namespace-sandbox.c:514: inferred mount options for /tmp/tmpbv6l5g_z/root: 0
src/namespace-sandbox/namespace-sandbox.c:551: mount: /etc/resolv.conf
src/namespace-sandbox/namespace-sandbox.c:514: inferred mount options for /tmp/tmpbv6l5g_z/etc/resolv.conf: 0
src/namespace-sandbox/namespace-sandbox.c:551: mount: /proc
src/namespace-sandbox/namespace-sandbox.c:514: inferred mount options for /tmp/tmpbv6l5g_z/proc: 14
src/namespace-sandbox/namespace-sandbox.c:561: mount: /home/frank/.ssh -> <sandbox>/nonexistent/.ssh (ro)
src/namespace-sandbox/namespace-sandbox.c:514: inferred mount options for /tmp/tmpbv6l5g_z/nonexistent/.ssh: 0
src/namespace-sandbox/namespace-sandbox.c:551: mount: /run/user/1000/keyring/ssh
src/namespace-sandbox/namespace-sandbox.c:480: cannot create /tmp/tmpbv6l5g_z/run/user: Read-only file system
```

**Comment by jkloetzke** [comment]
I think in your `sandbox::debian-stretch-x86_64` recipe there is a `mount` line which mounts `$SSH_AUTH_SOCK` into the sandbox. And in the sandbox image there is probably already a `/run` directory. Because the sandbox image itself is bind-mounted read-only this prevents the directory from being created...

**Comment by Ferruck** [comment]
Well, yes. So, to recap, the basic problem here is that the gnome-keyring opens its `SSH_AUTH_SOCK` within `/run` which is already present ro?!

**Comment by Ferruck** [comment]
But how to proceed from here? The user's `SSH_AUTH_SOCK` could be anywhere...

**Comment by jkloetzke** [comment]
That's the question. A possible option could be to mount `SSH_AUTH_SOCK` to a known-good location in the sandbox and set `SSH_AUTH_SOCK` to this location when using the sandbox. Another solution could be to patch the sandbox-helper/Bob to enable mounts that shadow existing files/directories.

**Comment by Ferruck** [comment]
Option two sounds error-prone to me. Option one may be a solution but is still a bit hacky IMHO.

TBH, the whole SSH with password protected keys thing within Bob is still, let's say, not optimal from a user's perspective. For example, if you've not yet added your key to the keyring and run `bob {build,dev} -j` your build will fail because the passphrase entry is hidden and will time out (at least that was the status quo the last time I tested it). Would it be unreasonable to expect Bob to handle such cases and maybe even provide `SSH_AUTH_SOCK` into the sandbox itself? That way, Bob could present the user the default pin-entry program and sandbox recipes wouldn't need to include multiple and always slightly wrong implementations of the above pattern of mounting `SSH_AUTH_SOCK` `$somewhere`...

**Comment by jkloetzke** [comment]
Since Bob 0.17 it is usually not necessary to mount the `SSH_AUTH_SOCK` into the sandbox any more. Bob now always executes the SCMs outside of the sandbox. The only reason why you would still have to use it is when your `checkoutScript` calls `git` itself, e.g. for submodules.

> Would it be unreasonable to expect Bob to handle such cases and maybe even provide `SSH_AUTH_SOCK` into the sandbox itself?

I'm usually reluctant to hard code special cases in Bob. What if Bob tries to mount the `SSH_AUTH_SOCK` to a path that you still want to use in the sandbox? That's certainly unlikely but would still require some configuration options.

> That way, Bob could present the user the default pin-entry program and sandbox recipes wouldn't need to include multiple and always slightly wrong implementations of the above pattern of mounting `SSH_AUTH_SOCK` `$somewhere`...

But what is the *right* (tm) pattern? And what about the `~/.ssh` directory that also needs to be mounted? In your current configuration it is mounted to `/nonexistent/.ssh`. That would differ if you use a sandbox with a different home directory of the `nobody` user.

**Comment by Ferruck** [comment]
> Since Bob 0.17 it is usually not necessary to mount the `SSH_AUTH_SOCK` into the sandbox any more. Bob now always executes the SCMs outside of the sandbox. The only reason why you would still have to use it is when your `checkoutScript` calls `git` itself, e.g. for submodules.

Well, that invalidates my whole point so the rest is just for completion and can safely be ignored:

> I'm usually reluctant to hard code special cases in Bob. What if Bob tries to mount the `SSH_AUTH_SOCK` to a path that you still want to use in the sandbox? That's certainly unlikely but would still require some configuration options.

If it's inside `/bob` it should be just as save as the workspaces.

> But what is the *right* (tm) pattern? And what about the `~/.ssh` directory that also needs to be mounted? In your current configuration it is mounted to `/nonexistent/.ssh`. That would differ if you use a sandbox with a different home directory of the `nobody` user.

That's a point indeed. I thought more about having Bob handle the whole SSH stuff internally (don't know if that's even possible), so looking up, showing pinentry programs and providing the right SSH keys to git (, svn, whatever) would be done by Bob itself rather than by the system's (maybe, probably, hopefully) running `ssh-agent`. Reading it written down I have to admit that this sounds quite out of scope for Bob, though.

**Comment by Ferruck** [comment]
I guess we can close this, or?
