### ISSUE TITLE
bob is a bottleneck

### ISSUE THREAD

**Issue by benjaminhampe** [BobBuildTool/bob#365]
Bob uncapable to produce 100% CPU usage
Mostly it uses 12,5% which is one single thread.

even though i use -j8 for my i7 6700K

Bob is a bottleneck. 

CMake is like 100 to 10000 faster, simply because its written in C++.

**Comment by jkloetzke** [comment]
Well, I think you mistakenly think Bob is something like CMake. This is not true. Bob is a package build system and in fact calls e.g. CMake, autotools, make, $whatever. This depends purely on the recipes. So if your project does not scale with the number of cores then there are simply no packages that can be built in parallel. Given your description I would assume that there is not even parallelism in your packages itself (the recipes should call `make -j`) because they only use one core. So without knowing the exact recipe dependencies and content it's hard to tell what is the bottleneck.

If you have a single package that is built with CMake you can go directly into the workspace (`build.sh shell` next to the workspace) and call CMake/make/nija yourself.

**Comment by benjaminhampe** [comment]
No, with pure cmake they build in parallel

**Comment by jkloetzke** [comment]
No, this has nothing to do with Bob itself. You could do the same with Bitbake, Conan or with any other meta build system of your preference and you still wouldn't be faster *given the same recipe structure*.

On the one hand you have your loved single source tree build. Every module next to each other and one single CMake+make/ninja call to build your application. Whatever meta build system is used it can never be faster than that.

On the other hand you have many recipes with their own dependency structure, each one with one or more modules inside. The modules in each recipe form a package. The recipe dependencies thus must be the union of all module depdencies it holds. Bob does not (and undoubtedly cannot) have any knowledge about the inner structure of such a package. In your case it's CMake, other recipes build autotools packages. Bob can just evaluate the dependencies between the recipes and try to build as many packages in parallel as possible. Now if your recipe structure is sub-optimal then Bob cannot do anything about it. Packages are the atoms of scheduling and a dependent package can only be built after *all* dependencies of that package have been built.

To make it more practical: suppose we have four modules with the following dependency structure: A-->B, A-->C, B-->D, C-->D. In an optimal schedule you can build B and C in parallel:

```
  /---> B ---\
 /            \
A              +--> D
 \            /
  \---> C ---/
```

If you would have one recipe for each module then Bob would be slower because the artifacts of a package need to be copied in the package step but the parallelism would be the same. Creating three recipes (R1[A] => R2[B, C] => R3[D]) would still preserve the parallelism of B and C. But imagine the following recipe structure: R1[A, B] => R2[C, D]:

```
 +--- R1 ---+ => +--- R2 ---+
 |          |    |          |
 |          |    |          |
 |    A ------------> C     |
 |    |     |    |    |     |
 |    v     |    |    v     |
 |    B ------------> D     |
 |          |    |          |
 +----------+    +----------+
```

In this case the parallelism is lost. Bob has to build R2 first. But inside of R2 there is no parallelism. The same is true for R1 which can only be built after R2 is finished. See what the problem is with sub-optimal recipes? This is something where Bob cannot "know better". And that's the core of your problem. Please talk to one of your integration guys and let them explain the recipe structure to you. Maybe some recipes can be split up or some modules can be moved between recipes to increase the parallelism between packages.

**Comment by benjaminhampe** [comment]
I can say that bob is a bottleneck because it is limited by the underlaying filesystem it uses to create .lock files and all the other files. If bob would do that in RAM or an RAMFS it would be much faster.

I can say that on HDD bob NEVER finishes
On SATA SSD it finishes after 7:30
With NVMe SSD it finishes in 29 min.

Bob is the bottleneck because it overuses the filesystem instead of the RAM.

**Comment by jkloetzke** [comment]
On which file system are you running? I've never seen such a huge impact.

How fast is `eatmydata bob ...` in comparison? This will effectively disable all safety guards against data corruption, though...

**Comment by benjaminhampe** [comment]
Xubuntu 18.04.5 LTS bionic. How about using a RAM-FS?

**Comment by benjaminhampe** [comment]
Ah ok,

256GB NVMe SSD ext4 -> also root filesystem /
512GB SATA SSD ntfs ( lets call it legacy, because there was someone using windows before me )
1TB HDD ntfs

ntfs sounds bad now?

**Comment by benjaminhampe** [comment]
Ok so eatmydata is a program that disables fsync() very specific but exactly what i need. Not bad. Retesting takes some time, i will add some results ( way ) later.

**Comment by jkloetzke** [comment]
I have no experience with NTFS but I can certainly imagine that `fsync()` is extremely costly on it. Let's see what the `eatmydata` results will be...

**Comment by benjaminhampe** [comment]
So i retested build from scratch with the ntfs sata ssd ( samsung 860, 512GB ) and built in 6:48:31 with eatmydata and icecc.
Means it was still so slow that it looks like i was building single threaded most of the time for my native 8 threader i7 6700K.

As another test I might format some part of sata evo ssd as ext4 and watch the difference.
cya

**Comment by benjaminhampe** [comment]
Hi, 

i formatted ntfs to ext4 and than built from scratch, took "only" 1:31:15. 

So i can say that NTFS is 5 times slower than EXT4 and should not be used.

Both tests were done with eatmydata bob dev .... -b -download no.

I guess we can close the issue now. Thanks for your help.

**Comment by jkloetzke** [comment]
Thanks for the info. Note that, depending on your recipes and target platform, a `bob dev --download no` might build more stuff than a plain CMake-Project that uses a pre-built SDK. Nevertheless there is still room for improvement and I'd keep the ticket open to investigate if anything of the following can be implemented safely:

* Only `fsync()` once when Bob finishes.
* Add an option to hash only for source changes. Currently Bob will re-scan the build workspace for manual changes.
