### ISSUE TITLE
understanding checkoutDeterministic

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#372]
Hey,

> checkoutDeterministic
> 
> Type: Boolean
> 
> By default any checkoutScript is considered indeterministic. The rationale is that extra care must be taken for a script to fetch always the same sources. If you are sure that the result of the checkout script is always the same you may set this to True. All checkoutSCMs on the other hand are capable of determining automatically whether they are determinstic.
> 
> If the checkout is deemed deterministic it enables Bob to apply various optimizations. It is also the basis for binary artifacts.

If we use "git" in `checkoutSCM` with `tag`, than we can set `checkoutDeterministic: True`.

Now we use the `user.yaml` to use `scmOverrides`, deletes the tag and adds a branch to a feature-branch. Is it necessary to set `checkoutDeterministic` to `False`? Is it possible to reset this?

BR.

**Comment by jkloetzke** [comment]
The wording needs some improvement I guess. :grinning: The `checkoutDeterministic` keyword only relates to the `checkoutScript` at the same level. If you have no `checkoutScript` then `checkoutDeterministic` implicitly defaults to `True`. Anything in `checkoutSCM` is not affected by `checkoutDeterministic`. For a SCM Bob is smart enough to figure that out by himself. So if you checkout a tag then Bob will know that *this* SCM is deterministic.

Because you cannot override a `checkoutScript` there is also no way to override `checkoutDeterminisic` either.

BTW, you can use the new `show` command to see if the package is actually considered deterministic. Bob will flag a package as deterministic if *all* `checkoutScript`s and *all* `checkoutSCM`s are deterministic.

**Comment by mahaase** [comment]
thx! I will update bob soon, including have a look into new features, for sure! 👍 
closed!
