### ISSUE TITLE
Build error: New SCM checkout 'example.server' collides with existing

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#378]
Is there something new and incompatible? if i delete the directory and restart it, everthing is fine, but...

`Build error: New SCM checkout 'example.server' collides with existing file in workspace 'dev/src/example/server/1/workspace'!`

**Comment by jkloetzke** [comment]
This is most probably a fallout of  #376. Does this still happen on latest master?

The Problem is that Bob has no entry in the workspace state that the module was previously checked out. This means a fresh checkout needs to be done and the error is a sanity check that there is nothing at the destination already. If you had built the workspace where #376 was *not* fixed the information about the checkout was lost and the next run will trigger the error.

**Comment by mahaase** [comment]
so I crashed my workspace by this issue, and i have to cleanup my src directory? (is no problem, was just a test-workspace)
I cleaned up the src-dir and everything works again! 

so issue could be closed?!

**Comment by jkloetzke** [comment]
Well, you do not have to remove the whole `dev/src/...` tree. But for every checkout that was done while the regression was present you will get an error. Anyway, the underlying problem is fixed...
