### ISSUE TITLE
replace tool-provided vars when replacing tools

### ISSUE THREAD

**Issue by rhubert** [BobBuildTool/bob#382]
In a depends we can replace tools by using

```
depends:
 - tools:
    foor: bar
   depends:
     -baz
```

which is useful, but does to not replace the `providedVars` by the tool's?

https://github.com/BobBuildTool/basement/blob/master/recipes/kernel/linux.yaml#L73 uses this but when CROSS_COMPILING in the target-toolchain is set the CROSS_COMPILE variable still set for the host tools build :( 

[foo.zip](https://github.com/BobBuildTool/bob/files/5602735/foo.zip) shows the issue:

```
$ bob dev root
[...]
>> root/foo
   PRUNE     dev/build/foo/1/workspace (recipe changed)
   BUILD     dev/build/foo/1/workspace
hello from tool A
MY_TOOL_VAR is B
[...]
```

**Comment by jkloetzke** [comment]
No the variable is not replaced  because `provideVars` and `provideTools` are unrelated to each other. Instead the variables should be provided with the tool definition. See [basement devel::cross-toolchain](https://github.com/BobBuildTool/basement/blob/d812049c8097577b7775a1eb7b9dcdf10a0bb457/recipes/devel/cross-toolchain.yaml#L28) for example. By attaching the variables to the tool they will be taken whenever the tool is actually used. See the [provideTools](https://bob-build-tool.readthedocs.io/en/latest/manual/configuration.html#providetools) docs for more details.

**Comment by rhubert** [comment]
Today is not my day... Thanks and sorry for the noise...
