### ISSUE TITLE
MSYS does NOT have gnu/libc-version.h header file

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#395]
so it isn't possible to build a host-tool.

```
Build error: Fingerprint script returned with 1
Failed package: amd64::windows/devel::win::parasoft-cpptest
Script output: + set -o pipefail
+ set -o nounset
+ set -o errexit
+ bob-libc-version gcc
+ type -p gcc
+ uname -m
+ cat
+ gcc -o conftest conftest.c
conftest.c:2:10: fatal error: gnu/libc-version.h: No such file or directory
    2 | #include <gnu/libc-version.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
+ cat
+ gcc -o conftest conftest.c
++ readelf -p .interp ./conftest
++ sed -n -e '/ld-musl/s/[^/]*\(\/.*\)/\1/p'
readelf: Error: Not an ELF file - it has the wrong magic bytes at the start
+ DL=
Script: set -o pipefail
set -o nounset
set -o errexit

bob-libstdc++-version()
{
    if ! type -p ${1:-${CXX:-c++}} >/dev/null ; then
        echo "No C++-Compiler!" >&2
        return 1
    fi

    # Machine type is important (e.g. x86_64)
    uname -m

    cat >conftest.cpp <<EOF
#include <iostream>
int main(int /*argc*/, char ** /*argv*/)
{
    int ret = 1;
#ifdef __GLIBCXX__
    std::cout << "libstdc++ " << __GLIBCXX__ << &std::endl;
    ret = 0;
#endif
#ifdef _LIBCPP_VERSION
    std::cout << "libc++ " << _LIBCPP_VERSION << &std::endl;
    ret = 0;
#endif
    return ret;
}
EOF
    ${1:-${CXX:-c++}} -o conftest conftest.cpp >/dev/null
    ./conftest
}


bob-libc-version()
{
    if ! type -p ${1:-${CC:-cc}} >/dev/null ; then
        echo "No C-Compiler!" >&2
        return 1
    fi

    # Machine type is important (e.g. x86_64)
    uname -m

    # Try glibc first
    cat >conftest.c <<EOF
#include <stdio.h>
#include <gnu/libc-version.h>
int main(){ printf("glibc %s\n", gnu_get_libc_version()); return 0; }
EOF
    if ${1:-${CC:-cc}} -o conftest conftest.c >/dev/null ; then
        ./conftest && return 0
    fi

    # Maybe musl libc? Link a simple program and extract runtime loader. On
    # musl the runtime loader is executable and outputs its version.
    cat >conftest.c <<EOF
int main(){ return 0; }
EOF
    if ! ${1:-${CC:-cc}} -o conftest conftest.c >/dev/null ; then
        echo "The C-Compiler does not seem to work... :(" >&2
        return 1
    fi

    DL=$(readelf -p .interp ./conftest | sed -n -e '/ld-musl/s/[^/]*\(\/.*\)/\1/p')
    if [[ -x $DL ]] ; then
        $DL 2>&1 || true
        return 0
    fi

    # Uhh?
    echo "Unsupported system. Please consider submitting your OS configuration for inclusion." >&2
    return 1
}

bob-libc-version gcc
bob-libstdc++-version g++
```

**Comment by jkloetzke** [comment]
Any suggestions how to properly determine the libc version on MSYS? I have not found anything useful so far.

**Comment by daxcore** [comment]
Hm: `The GNU C library is currently unavailable for this platform.`

MSYS2 doesn't use glibc. this tests for fingerprint will not work.
I guess we have to deactivate this tests to build msys2 host sw?!

**Comment by jkloetzke** [comment]
The test is not about glibc but about the standard C library in general. I'm aware that msys does not use glibc but something else. The result of the `bob-libc-version` test should make sure that a program linked one one system is able to run on another system. So for MSYS it may be as simple as using the dll name itself.

> I guess we have to deactivate this tests to build msys2 host sw?!

This is not a good idea. If MSYS would ever introduce a new version (e.g. `msys-2.1.dll`) then your old built artifacts would not run because they miss the right dll. This is exactly what this fingerprint test should prevent.

> Or the alternative is, to provide the vs-toolchain at the very beginning of the windows root-recipe?!
> So we won't build anything with MSYS. Cross-compiling in windows makes no sense at all.

If you execute Bob in MSYS you are *not* on native Windows. Compiling with the VS-Toolchains is in fact cross-compiling. :) This would be exatly the oposite if you execute Bob with a native Python and use PowerShell scripts. In this case the `bob-libc-version`should determine the msvcrt.dll version instead because it is the native C library.

**Comment by daxcore** [comment]
Push. Corrently the windows host-toolchain can not be used.

**Comment by jkloetzke** [comment]
I'll look into it.
