### ISSUE TITLE
noUndefinedTools policy not working with forwarded tools

### ISSUE THREAD

**Issue by danielroedl** [BobBuildTool/bob#419]
Hi,

there is a problem with the `noUndefinedTools` policy in bob 0.19. If a tool is forwarded in a recipe to it's dependencies with `forward: True` bob claims that the tool is missing.
Is this the indented behaviour?

You can reproduce the problem by using https://github.com/BobBuildTool/bob-example-containers and changing the bob minimum version to 0.19.1.

**Comment by jkloetzke** [comment]
Just bumping the minimum version (and thus implicitly setting the `noUndefinedTools` policy) will not work because the repository references an old commit of basement. There was at least [this commit](https://github.com/BobBuildTool/basement/commit/83411dbe9fae421b67cb188f0fb77f1f636e44c7) related to the policy. If you switch `layers/basement` to the master branch it should parse.

**Comment by jkloetzke** [comment]
Feel free to reopen if you still have problems.
