### ISSUE TITLE
using artifacts but no access to sources

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#427]
hey.

is it be possible to change the artifact handling in bob, that a user can download prebuilt artifacts, also if he hasn't access to the e.g. git-sources.

in our case, the sources of a module have restrictions. just project member are able to read and write the sources. but the built module shall be used in another bob project.

br.

**Comment by jkloetzke** [comment]
If the module uses a commit-Id and is built exactly the same way in the other project it should work already. But you will have to make sure that all used classes, toolchains and dependencies are exactly the same.

What does not really work are git checkouts that use a tag. Bob will still do a `git ls-remote` in this case. The reason is that a tag could be changed/overwritten. While this is strongly discouraged by git there is nothing preventing doing that. This is why Bob will always check which commit the tag is pointing at. Is this the problem or does it even not work for you with commit IDs?

**Comment by mahaase** [comment]
we'll test it! thanks so far! :)

**Comment by jkloetzke** [comment]
Have you got any insight so far if this works?

**Comment by jkloetzke** [comment]
Ping...

**Comment by mhofmannFDT** [comment]
We tested it using commit ids. A previously uploaded artifact was downloaded during build (bob dev) in another (clean) workspace. So looks like it works. However, we have not tested the build step so far when access to sources is restricted.

**Comment by jkloetzke** [comment]
Feel free to re-open if this is still an issue.
