### ISSUE TITLE
Always use python as extractor on native Windows

### ISSUE THREAD

**Issue by sbixl** [BobBuildTool/bob#496]
If a extractor program like "unzip" is installed in the local file system on a native windows machine, permisson denied problems may occur. We run into this issue while updating some Orcale stuff which ships a internal "unzip.exe".

I would suggest that we only use the internal Python extractor while running under native Windows?

**Comment by jkloetzke** [comment]
I'm not entirely sure. The python version was always meant to be a fallback if a native program is missing. There may be zip files that cannot be extracted by the python version or that are handled differently by the Python implementation.

Could you find out what the root cause of the "permission denied" problems was exactly? Did you have to patch the Bob sources or was there another workaround? I'm a bit reluctant to change a default that has worked so far...

**Comment by sbixl** [comment]
I will close this issue because it is no more reproducible. If it happen again I will try to dive deeper in order to provide more detailed Information.

**Comment by jkloetzke** [comment]
Right now there is no function to control which extractor is used. Bob does already see if a matching extractor is available in `%PATH%`. But of course only the *presence* is detected.

I don't think it makes sense to "test" if the extractor is really working. That requires special handling per extractor. Because simply calling the exe will likely fail (exit code > 0) because the command expects a file. It would require dummy archives that are extracted. I don't see that it's worth the effort. Wouldn't it be much easier to fix the root cause..?

**Comment by sbixl** [comment]
In any case, the problem should be eliminated in its cause. I just thought it might be useful to have a way to remove certain paths from the PATH variable via a blacklist. A use case could be for example a path that has to be available by company policy in the path variable but can lead to problems in interaction with bob. 

Currently we don't have such a problem it was just a hypothetical consideration to have the contents of the PATH variables under windows more under control.
